# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'rubocop', require: false

gem 'sinatra'

gem 'rerun'

gem 'puma'

gem 'rspec'

gem 'simplecov'

gem 'capybara'


# gem "rails"
