AllCops:
  TargetRubyVersion: 2.5
Metrics/AbcSize:      # Отключение ABC-проверок
  Enabled: false
Metrics/LineLength:   # Длина строк 120
  Max: 120
Metrics/MethodLength: # Количество строк кода 15
  Max: 15
Style/NegatedIf:      # Не форсировать 
  Enabled: false
  